INSERT INTO t_p17413487_future_vision_projec.menu_items (category, name, description, price, price_bottle, price_glass, sort_order) VALUES
('cocktails_author', 'Lavande Spritz', 'лаванда, просекко, лимон', 650, NULL, NULL, 1),
('cocktails_author', 'Cyan Lagoon', 'голубой кюрасао, лайм, тоник', 600, NULL, NULL, 2),
('cocktails_author', 'Milk Punch', 'молоко, ром, ваниль, специи', 700, NULL, NULL, 3),
('cocktails_author', 'G80 Heart', 'малина, роза, джин, личи', 750, NULL, NULL, 4),
('cocktails_author', 'Donbass', 'авторский коктейль бара', 600, NULL, NULL, 5),
('cocktails_classic', 'Mojito', 'ром, мята, лайм', 550, NULL, NULL, 1),
('cocktails_classic', 'Aperol Spritz', 'апероль, просекко', 600, NULL, NULL, 2),
('cocktails_classic', 'Margarita', 'текила, лайм, трипл-сек', 550, NULL, NULL, 3),
('cocktails_classic', 'Cosmopolitan', 'водка, клюква, лайм', 500, NULL, NULL, 4),
('cocktails_classic', 'Long Island', '5 видов алкоголя, кола', 700, NULL, NULL, 5),
('cocktails_classic', 'Daiquiri', 'ром, лайм, сахар', 500, NULL, NULL, 6),
('shots_author', 'Blow Job', 'бейлис, взбитые сливки', 450, NULL, NULL, 1),
('shots_author', 'KuniLi', 'лаймовый ликёр, мята, ром', 450, NULL, NULL, 2),
('shots_author', 'Камшот', 'сливочный ликёр, кокос', 450, NULL, NULL, 3),
('shots_author', 'Точка G', 'гренадин, малина, водка', 450, NULL, NULL, 4),
('shots_author', 'БДСМ', 'бурбон, дым, специи', 450, NULL, NULL, 5),
('shots_author', 'Dirty Talk', 'текила, перец, лайм', 450, NULL, NULL, 6),
('shots_classic', 'Б-52', 'калуа, бейлис, куантро', 450, NULL, NULL, 1),
('shots_classic', 'Ягербомб', 'ягермайстер + энергетик', 450, NULL, NULL, 2),
('shots_classic', 'Самбука', 'классика с зёрнами кофе', 450, NULL, NULL, 3),
('shots_classic', 'Текила', 'соль, лайм', 450, NULL, NULL, 4),
('shots_classic', 'Клубничный взрыв', 'малиновый ликёр, водка', 450, NULL, NULL, 5),
('whiskey', 'Jack Daniel''s', 'виски', 550, 6500, NULL, 1),
('whiskey', 'Jim Beam', 'виски', 500, 5500, NULL, 2),
('whiskey', 'Jameson', 'виски', 550, 8000, NULL, 3),
('whiskey', 'Ballantine''s', 'виски', 500, 5000, NULL, 4),
('whiskey', 'Арарат 5★', 'коньяк', 250, 3000, NULL, 5),
('whiskey', 'Арарат 3★', 'коньяк', 250, 3000, NULL, 6),
('hookah', 'Два Яблока', NULL, 1400, NULL, NULL, 1),
('hookah', 'Виноград Мята', NULL, 1400, NULL, NULL, 2),
('hookah', 'Арбуз', NULL, 1400, NULL, NULL, 3),
('hookah', 'Клубника Банан', NULL, 1400, NULL, NULL, 4),
('hookah', 'Лесные ягоды', NULL, 1400, NULL, NULL, 5),
('hookah_premium', 'Белый виноград на молоке', NULL, 1600, NULL, NULL, 1),
('hookah_premium', 'Тропический коктейль', NULL, 1600, NULL, NULL, 2),
('hookah_premium', 'Чёрная смородина на льду', NULL, 1600, NULL, NULL, 3),
('hookah_premium', 'Роза лаванда', NULL, 1600, NULL, NULL, 4),
('hookah_premium', 'Экзотические фрукты', NULL, 1600, NULL, NULL, 5),
('beer', 'Corona', NULL, 350, NULL, NULL, 1),
('beer', 'Bud', NULL, 250, NULL, NULL, 2),
('beer', 'Tuborg', NULL, 300, NULL, NULL, 3),
('beer', 'Hoegaarden', NULL, 400, NULL, NULL, 4),
('beer', 'Балтика 0', NULL, 250, NULL, NULL, 5),
('wine', 'Просекко', NULL, NULL, 2000, 500, 1),
('wine', 'Асти', NULL, NULL, 2000, 500, 2),
('wine', 'Белое сухое', NULL, NULL, 2000, 500, 3),
('wine', 'Красное полусладкое', NULL, NULL, 2000, 500, 4),
('wine', 'Розовое', NULL, NULL, 2000, 500, 5),
('energy', 'Red Bull', NULL, 350, NULL, NULL, 1),
('energy', 'Burn', NULL, 250, NULL, NULL, 2),
('energy', 'Adrenaline Rush', NULL, 350, NULL, NULL, 3),
('drinks', 'Coca-Cola', NULL, 250, NULL, NULL, 1),
('drinks', 'Fanta', NULL, 250, NULL, NULL, 2),
('drinks', 'Sprite', NULL, 250, NULL, NULL, 3);